highbd_pickrst_neon.c: fix MSVC build
Use vld1_s32() rather than an array initializer; neon types are defined
as a union with MSVC. Fixes:

av1\encoder\arm\neon\highbd_pickrst_neon.c(753,33): error C2078: too many initializers

Change-Id: I9b3cc7cfe76607642c8b2a8701e0f3f93c7d00e1