partition_search: Fix implicit declaration
Example warning:

```c
av1/encoder/partition_search.c: In function 'setup_block_rdmult':
av1/encoder/partition_search.c:432:5: warning: implicit declaration of function 'av1_set_vmaf_rdmult'; did you mean 'av1_set_ssim_rdmult'? [-Wimplicit-function-declaration]
  432 |     av1_set_vmaf_rdmult(cpi, x, bsize, mi_row, mi_col, &x->rdmult);
      |     ^~~~~~~~~~~~~~~~~~~
      |     av1_set_ssim_rdmult
```

Change-Id: I6dd2c888a983f63bb1e251da0d35dd25b4e957a4
(cherry picked from commit 8aa234e78c7fa5636d2c69abdaf64629bd9d9aaa)