Do not use #if inside assert()
Fix the Visual C++ compilation errors:
aom\av1\encoder\ratectrl.c(1024,1): error C2121: '#': invalid character:
possibly the result of a macro expansion [build\aom_av1_encoder.vcxproj]
av1\encoder\ratectrl.c(1024,1): error C2059: syntax error: 'if'
[build\aom_av1_encoder.vcxproj]

Change-Id: Ifcdddc18513e5b5e9afbf682bfa9bc9c53ca056c
(cherry picked from commit 8c113ea88bc5afc1d5d7001c8dedbde7af2c82dc)