Add missing header for EBUSY on mingw
The `error: use of undeclared identifier 'EBUSY'` in
vpx_util/vpx_pthread.h was found in Mozilla's bug 1886318 [1]. This
patch addresses the issue by adding the `<errno.h>` header to introduce
the `EBUSY` identifier, resolving the problem.

This patch is based on the change in libvpx:
0752960c6 Add missing header for EBUSY on mingw
https://chromium-review.googlesource.com/c/webm/libvpx/+/5425372

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1886318#c1

Change-Id: I90bd6b605613094fe2decfa48831f98941108a6c