fadst8x4_neon: use intrinsics for vector mult
This fixes a build error with Microsoft's compiler:
av1\encoder\arm\neon\av1_fwd_txfm2d_neon.c(472,13): error C2088: '*':
  illegal for union
av1\encoder\arm\neon\av1_fwd_txfm2d_neon.c(472,13): error C2440:
  'function': cannot convert from 'int' to '__n64'

Change-Id: I1c746c1bc58ffa0b628bb8cfc4b583c6f5a89fc6