encoder_utils: Fix implicit declaration
Example warning:

```c
av1/encoder/encoder_utils.c: In function 'av1_determine_sc_tools_with_encoding':
av1/encoder/encoder_utils.c:976:11: warning: implicit declaration of function 'av1_get_vmaf_base_qindex'; did you mean 'av1_get_txb_size_index'? [-Wimplicit-function-declaration]
  976 |           av1_get_vmaf_base_qindex(cpi, q_for_screen_content_quick_run),
      |           ^~~~~~~~~~~~~~~~~~~~~~~~
      |           av1_get_txb_size_index
```

Change-Id: Ida5b64aecb1435f4d755e7006952bb691498b43d
(cherry picked from commit 391b12f0846d9d65123cb21c68c600c3138df0e8)