Fix a copy-paste error in get_partition()
Fix Coverity defect CID 329379:
  original: sshigh * 2 == bhigh looks like the original copy.

  CID 329379: (#1 of 1): Copy-paste error (COPY_PASTE_ERROR)
  copy_paste_error: bhigh in sswide * 2 == bhigh looks like a
  copy-paste error.

  Should it say bwide instead?

This bug was introduced in
https://aomedia-review.googlesource.com/c/aom/+/20901.

Change-Id: I289fd7bb8bfe3856d6ab2a5bcb10faadb8ff9cdd