fix encode_api_test.cc compilation w/MSVC
after:
8e8b06725f Fix test for CONFIG_REALTIME_ONLY.

preprocessor checks can't be used within macros:
test\encode_api_test.cc(351,1): error C2121: '#': invalid character:
possibly the result of a macro expansion

Change-Id: I7c357ce1ce816c3c3c80ae449eae8330d7f26836
(cherry picked from commit 32a0216dd395d7012ea89ea3c5883e8864984f9a)