README.md: fix gcloud storage role
Use `roles/storage.legacyObjectReader` instead of `roles/objectViewer`.

Fixes:
```
ERROR: (gcloud.storage.objects.add-iam-policy-binding) HTTPError 400:
roles/storage.objectViewer is not a valid role for
projects/_/buckets/aom-test-data/objects/...
```

See also:
 https://docs.cloud.google.com/storage/docs/access-control/iam-roles

Bug: 512387213
Change-Id: Ic404394bad3e91fa815c05571aee89b273442e51